#!/bin/bash
function logoPrint(){

COLUMNS=$(tput cols) 
title=$(echo -e "\e[94m

		 ▄████▄   ▒█████   ███▄ ▄███▓ ▄▄▄▄    ▒█████  
		▒██▀ ▀█  ▒██▒  ██▒▓██▒▀█▀ ██▒▓█████▄ ▒██▒  ██▒
		▒▓█    ▄ ▒██░  ██▒▓██    ▓██░▒██▒ ▄██▒██░  ██▒
		▒▓▓▄ ▄██▒▒██   ██░▒██    ▒██ ▒██░█▀  ▒██   ██░
		▒ ▓███▀ ░░ ████▓▒░▒██▒   ░██▒░▓█  ▀█▓░ ████▓▒░
		░ ░▒ ▒  ░░ ▒░▒░▒░ ░ ▒░   ░  ░░▒▓███▀▒░ ▒░▒░▒░ 
		  ░  ▒     ░ ▒ ▒░ ░  ░      ░▒░▒   ░   ░ ▒ ▒░ 
		░        ░ ░ ░ ▒  ░      ░    ░    ░ ░ ░ ░ ▒  
		░ ░          ░ ░         ░    ░          ░ ░  
		░                                  ░          
		 ▄████▄   ██▓    ▓█████ ▄▄▄       ███▄    █   
		▒██▀ ▀█  ▓██▒    ▓█   ▀▒████▄     ██ ▀█   █   
		▒▓█    ▄ ▒██░    ▒███  ▒██  ▀█▄  ▓██  ▀█ ██▒  
		▒▓▓▄ ▄██▒▒██░    ▒▓█  ▄░██▄▄▄▄██ ▓██▒  ▐▌██▒  
		▒ ▓███▀ ░░██████▒░▒████▒▓█   ▓██▒▒██░   ▓██░  
		░ ░▒ ▒  ░░ ▒░▓  ░░░ ▒░ ░▒▒   ▓▒█░░ ▒░   ▒ ▒   
		  ░  ▒   ░ ░ ▒  ░ ░ ░  ░ ▒   ▒▒ ░░ ░░   ░ ▒░  
		░          ░ ░      ░    ░   ▒      ░   ░ ░   
		░ ░          ░  ░   ░  ░     ░  ░         ░   
		░                                             
 ")
clear
printf "%*s\n" $(((${#title}+$COLUMNS)/2)) "$title"

}

function statusPrint(){
	if [[ "$1" == "error" ]]; then
		logoPrint
		echo -e "\e[91m[Error]\e[39m Try: combolist --help"
	else
		logoPrint
		echo -e "\e[32m[Sucess]\e[39m | by \e[96mi386angel"
	fi
}

function fileClear(){
	if [[ -f "$1" ]]; then
		cat "$1" | cut -f 1 -d ':' >> "$2"
		sed -i '/^$/d' "$2"
	else
		echo ' ' > "$2"
		cat "$1" | cut -f 1 -d ':' >> "$2"
		sed -i '/^$/d' "$2"
	fi
}

if [[ $1 ]]; then
	case $1 in
		"-h" | "--help" )
			echo "Use: comboclean -f FILE_NAME -o OUTPUT_FILE_NAME"	;;
		"-f" | "--file" )
			if [[ $2 ]]; then
				if [[ "$3" == "-o" ]]; then
					fileClear $2 $4
					statusPrint
				else
					statusPrint error
				fi
			else
				statusPrint error
			fi ;;
		* )
		statusPrint error ;;
	esac
else
	statusPrint error
fi